version: '3.8'

services:
  eureka-server:
    build:
      context: ./Service-Discovery
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - spring-cloud

  user-service:
    build:
      context: ./User-Service
      dockerfile: Dockerfile
    depends_on:
      - eureka-server
    ports:
      - "8010:8010"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - spring-cloud
    volumes:
      - ~/.m2:/root/.m2

  car-service:
    build:
      context: ./CarService
      dockerfile: Dockerfile
    depends_on:
      - eureka-server
    ports:
      - "8020:8020"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - spring-cloud
    volumes:
      - ~/.m2:/root/.m2

  rental-service:
    build:
      context: ./CarRentalService
      dockerfile: Dockerfile
    depends_on:
      - eureka-server
      - user-service
      - car-service
    ports:
      - "8030:8030"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - spring-cloud
    volumes:
      - ~/.m2:/root/.m2

  api-gateway:
    build:
      context: ./Api-Gateway
      dockerfile: Dockerfile
    depends_on:
      - eureka-server
    ports:
      - "8765:8765"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - spring-cloud
    volumes:
      - ~/.m2:/root/.m2

networks:
  spring-cloud:
