version: '3.8'

services:
  eureka-server:
    build:
      context: .
      dockerfile: ./Service-Discovery/Dockerfile
    ports:
      - "8761:8761"
    networks:
      - spring-cloud

  user-service:
    build:
      context: .
      dockerfile: ./User-Service/Dockerfile
    depends_on:
      - eureka-server
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - spring-cloud

  car-service:
    build:
      context: .
      dockerfile: ./CarService/Dockerfile
    depends_on:
      - eureka-server
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - spring-cloud

  rental-service:
    build:
      context: .
      dockerfile: ./CarRentalService/Dockerfile
    depends_on:
      - eureka-server
      - user-service
      - car-service
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - spring-cloud

  api-gateway:
    build:
      context: .
      dockerfile: ./Api-Gateway/Dockerfile
    depends_on:
      - eureka-server
    ports:
      - "8765:8765"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - spring-cloud

networks:
  spring-cloud:
